services:

  aws-cli:
    image: frontandstart/terraform-cloud:aws
    build:
      target: aws
      context: .
    volumes:
      - aws-data:/root

  gcp-cli:
    image: frontandstart/terraform-cloud:gcp
    build:
      target: gcp
      context: .
    volumes:
      - gcp-data:/root
  
  azure-cli:
    image: frontandstart/terraform-cloud:azure
    build:
      target: azure
      context: .
    tty: true
    volumes:
      - azure-data:/root

  digitalocean-cli:
    image: frontandstart/terraform-cloud:digitalocean
    build:
      target: digitalocean
      context: .
    volumes:
      - do-data:/root
    tty: true

volumes:
  aws-data:
  gcp-data:
  azure-data:
  do-data: