name: 'Build and Push Docker Images'

on:
  push:
    branches:
      - "main"

  schedule:
    - cron: '0 2 * * 1'

env:
  DOCKER_BUILKIT: 1
  DOCKER_IMAGE: frontandstart/terraform-cloud

jobs:
  build:
    name: Build docker images
    strategy:
      matrix:
        cloud: ['aws', 'gcp', 'azure', 'do']
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ matrix.cloud }} --target terraform-cloud-${{ matrix.cloud }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ matrix.cloud }}
