name: 'Build and Push Docker Images'

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docker-compose.yml'
    branches:
      - "main"
    
      
  schedule:
    - cron: '0 2 * * 1'

env:
  DOCKER_BUILKIT: 1
  DOCKERHUB_USERNAME: frontandstart
  DOCKERHUB_REPOSITORY: terraform-cloud

jobs:


  build:
    name: Build docker images
    strategy:
      matrix:
        cloud: ['aws', 'gcp', 'azure', 'digitalocean']

    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build Images cloud images
        run: |
          docker build --tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ matrix.cloud }} \
                       --target ${{ matrix.cloud }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ matrix.cloud }}
